import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Navbar } from "@/app/components/navbar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex min-h-screen flex-col items-center`}
      >
        <Navbar />

        <main className="w-full flex-1 p-24">{children}</main>
      </body>
    </html>
  );
}
